# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='pic',
            field=models.ImageField(default='', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
